name: 'NPM'
description: 'Install private NPM packages'
inputs:
  NODE_VERSION:
    description: Node JS version
    default: "20.x"
    required: false
    type: string
secrets:
  NPM_TOKEN:
    description: Token for private NPM packages
    required: false

runs:
  using: composite
  env:
    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        registry-url: "https://npm.pkg.github.com"
        scope: "@${{ github.repository_owner }}"

    - uses: bahmutov/npm-install@v1
