name: 'NPM'
description: 'Install private NPM packages'
inputs:
  NODE_VERSION:
    description: Node JS version
    default: "20.x"
    required: false
    type: string
secrets:
  NPM_TOKEN:
    description: Token for private NPM packages
    required: false

runs:
  using: composite
  defaults:
    run:
      shell: bash
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.NODE_VERSION }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Set up NPM auth
      run: |
        npm config set //npm.pkg.github.com/:_authToken ${{ secrets.NPM_TOKEN }}
        npm config set @mindkomm:registry http://npm.pkg.github.com/

    - uses: bahmutov/npm-install@v1
