name: Release

on:
  workflow_call:
    outputs:
      created:
        description: "A boolean value that indicates if a release has been created"
        value: ${{ jobs.release.outputs.created }}
      tag:
        description: "The created version tag name"
        value: ${{ jobs.release.outputs.tag }}

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.release-please.outputs.release_created }}
      tag: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release-please
