on:
  workflow_call:
    inputs:
      package_name:
        required: false
        type: string
        description: "Custom name for the package (defaults to repository name)"
    secrets:
      READ_PACKAGES_TOKEN:
        description: Read packages token
        required: true
      COMPOSER_AUTH_JSON:
        description: Authentication for privately hosted packages and repositories as a JSON formatted object.
        required: true
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: "The tag to create the package for"
      package_name:
        required: false
        type: string
        description: "Custom name for the package (defaults to repository name)"

name: Release

jobs:
  release:
    # Only run when not manually triggered
    if: "${{ github.event.inputs.tag == '' }}"
    uses: mindkomm/workflows/.github/workflows/release.yml@main

  create-package:
    runs-on: ubuntu-latest
    needs: release
    if: |
      always() &&
      needs.release.result == 'skipped' ||
      (needs.release.outputs.created || github.event.inputs.tag != '')
    env:
      COMPOSER_AUTH: "${{ secrets.COMPOSER_AUTH_JSON }}"
      PACKAGE_NAME: ${{ inputs.package_name != '' && inputs.package_name || github.event.repository.name }}
    steps:
    # Set current tag, either from the release event or from the workflow_call event
    - run: echo "TAG=${{ github.event.inputs.tag != '' && github.event.inputs.tag || needs.release.outputs.tag }}" >> $GITHUB_OUTPUT
      id: tag

    # Set zip file name
    - run: echo "ZIP_FILENAME=${{ env.PACKAGE_NAME }}-${{ steps.tag.outputs.TAG }}.zip" >> $GITHUB_OUTPUT
      id: zip-filename

    - uses: actions/checkout@v5
      with:
        path: repo
        ref: ${{ steps.tag.outputs.TAG }}

    # Archive the repository, so we get all files without the .git directory and exluded files from .gitattributes
    - run: |
        cd repo
        ls -la
        git archive --output $GITHUB_WORKSPACE/${{ steps.zip-filename.outputs.ZIP_FILENAME }} ${{ steps.tag.outputs.TAG }}
        cd $GITHUB_WORKSPACE
        rm -rf repo
        unzip $GITHUB_WORKSPACE/${{ steps.zip-filename.outputs.ZIP_FILENAME }}
        rm -rf $GITHUB_WORKSPACE/${{ steps.zip-filename.outputs.ZIP_FILENAME }}
        ls -la

    # Get PHP version from .php-version file
    - run: echo PHP_VERSION=$(cat .php-version) >> $GITHUB_OUTPUT
      id: php-version

    # Install Composer dependencies
    - uses: mindkomm/workflows/.github/actions/composer@main
      with:
        COMPOSER_ARGS: --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader --classmap-authoritative --verbose
        PHP_VERSION: ${{ steps.php-version.outputs.PHP_VERSION }}
        COMPOSER_CONFIG: ${{ vars.COMPOSER_CONFIG_JSON }}

    # Install NPM dependencies
    # - uses: ./.github/actions/npm
    #   env:
    #   NPM_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}

    - uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Set up NPM auth
      run: |
        npm config set //npm.pkg.github.com/:_authToken ${{ secrets.READ_PACKAGES_TOKEN }}
        npm config set @mindkomm:registry http://npm.pkg.github.com/

    - uses: bahmutov/npm-install@v1

    # Build assets
    - run: npm run build
      env:
        NODE_ENV: production

    # Remove unnecessary files
    - run: |
        rm -rf node_modules assets assets-editor
        find . -type f -maxdepth 1 \( -name "webpack.config.js" -o -name "webpack.mix.js" -o -name "package.json" -o -name "package-lock.json" -o -name "babel.config.json" \) -exec rm {} \;

    # Compress all text files (gz and br) to be served as precompressed
    - run: |
        find . -type f \( -iname \*.css -o -iname \*.js -o -iname \*.svg -o -iname \*.html -o -iname \*.ics \) -exec gzip -k -9 -f {} \;
        find . -type f \( -iname \*.css -o -iname \*.js -o -iname \*.svg -o -iname \*.html -o -iname \*.ics \) -exec brotli  -f {} \;

    # Zip the package
    - run: |
        mkdir $GITHUB_WORKSPACE/../tmp
        mv $GITHUB_WORKSPACE/* $GITHUB_WORKSPACE/../tmp
        mkdir $GITHUB_WORKSPACE/${{ env.PACKAGE_NAME }}
        mv $GITHUB_WORKSPACE/../tmp/* $GITHUB_WORKSPACE/${{ env.PACKAGE_NAME }}
        zip -r -q $GITHUB_WORKSPACE/${{ steps.zip-filename.outputs.ZIP_FILENAME }} ${{ env.PACKAGE_NAME }}

    # Upload the package to the release
    - uses: AButler/upload-release-assets@v3.0
      with:
        files: "${{ steps.zip-filename.outputs.ZIP_FILENAME }}"
        release-tag: ${{ steps.tag.outputs.TAG }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
